In [5]:
import numpy as np

# How to create arrays

In [195]:
def foo(a: int, b: float) -> float:
    return "hello"

In [56]:
u = np.array([1, 2, 3])
v = np.array([6, 7, 8], dtype = float)

In [57]:
u + v

array([ 7.,  9., 11.])

In [61]:
m = np.array([
    [1,2, 3],
    [4, 5, 6],
], dtype = float)

In [22]:
m.shape

(2, 3)

In [34]:
m.dtype

dtype('float64')

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [76]:
np.zeros((3, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Some useful operations

In [63]:
# Matrix multiplcation
m @ m.T

array([[14., 32.],
       [32., 77.]])

In [65]:
m.dot(m.T)

array([[14., 32.],
       [32., 77.]])

In [64]:
m.T @ m

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

## Broadcasting

In [93]:
x = np.arange(9).reshape((3, 3))
y = np.array([10, 20, 30])

In [89]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
np.ones(3) + 3

array([4., 4., 4.])

In [94]:
x + y 

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38]])

In [21]:
20 * m + m 

array([[ 21,  42,  63],
       [ 84, 105, 126]])

## Operations on axis

In [100]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [108]:
x.shape

(2, 3)

In [103]:
np.max(x)

5

In [104]:
np.max(x, axis = 0)

array([3, 4, 5])

In [105]:
np.max(x, axis = 1)


array([2, 5])

## Concatenation / stacking

In [119]:
x = np.arange(3)
y = np.arange(3, 6)
x, y

(array([0, 1, 2]), array([3, 4, 5]))

In [123]:
x + y

array([3, 5, 7])

In [126]:
np.concatenate([x, y], axis = 0)

array([0, 1, 2, 3, 4, 5])

In [131]:
# Error because x, y are not 2d
np.concatenate([x, y], axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [136]:
# Creates a new axis and concatenates them along that axis
np.stack([x, y], axis = 0)

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [145]:
x = np.arange(49).reshape((7, 7))
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [174]:
x[1:7:2, :]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27],
       [35, 36, 37, 38, 39, 40, 41]])

In [178]:
x[:, 1:7:2]

array([[ 1,  3,  5],
       [ 8, 10, 12],
       [15, 17, 19],
       [22, 24, 26],
       [29, 31, 33],
       [36, 38, 40],
       [43, 45, 47]])

In [184]:
x[1:4:2, 2:5:2]

array([[ 9, 11],
       [23, 25]])

In [158]:
l = list(range(10, 70, 10))
l

[10, 20, 30, 40, 50, 60]

In [159]:
l[3:]

[40, 50, 60]

In [160]:
l[2:6]

[30, 40, 50, 60]

In [161]:
l[:-1]

[10, 20, 30, 40, 50]